language: node_js
node_js:
- '8'
sudo: false
os:
- linux
cache:
  directories:
  - node_modules
install:
- yarn install
- yarn build
script:
- yarn run lint
- yarn run test --silent
deploy:
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    api_key:
      secure: dajqLCZzFOAf3QZ2ZLF5ontjaduVzFJN2SjP0SK+aGiIHq7G+kWg1shj6stAzh17xUMl7K1L8xn16zKMT3zM9KTt30KpByoUJwVKEuvHdEaY5y3n8PtRx9YUoNotOscu1p1gx4raEfJY8gtfeyA0RS/n1oQPE3YPW9J/Vx9UOJkXdynEECmP7Onzsz1/GS4SfZCS/gt58dOp9hcIpOiSqs9H5fh8R0SvMHa1cfh6JAYt46pJZZClXvrpzMeZ/Hg2p4dWmoVREe5E3MtRw+JQfS5kFbi9JYH8NTNiAwOPiaknUlidXLaLvLzlOQOy0f8u5R8m9IZApRxDLcHTGMVYsPsxscL0fEwT8G2/r6EZqVQDtDxAoZZQg7+/nuvejSVtcnU8P6lU+T44ljGn6dkHZcrnNOY9co8Lk2wYJd6pI60DgMICDzMk937s7eSmOADM1RMjQ59D8EfNDj4+Xd8fFy4hbTeNZMttsCQ1ViqD4cKWsJ257zoimllSNBVnTg3tgmZLJzlyYCAZ6dAw/+7kwgT40qUhjmwkFyWHyOiAyDGQu9faL4U+6JprtZZuuUlOb7wRaRFSGorsSIhX1hdc1LRClWsV/IXV7ppvg75CWZSF1QA/SGZYn/LTYZ+zyawUFcf+yA53FI5dX9hSoYv4FPLrDMW4jOQaXOh3q6XbMj0=
    on:
      branch: master
      condition: "`./scripts/checkTag.sh` = RELEASE"
  - provider: npm
    email: dev@xcomponent.com
    skip_cleanup: true
    tag: next
    api_key:
      secure: dajqLCZzFOAf3QZ2ZLF5ontjaduVzFJN2SjP0SK+aGiIHq7G+kWg1shj6stAzh17xUMl7K1L8xn16zKMT3zM9KTt30KpByoUJwVKEuvHdEaY5y3n8PtRx9YUoNotOscu1p1gx4raEfJY8gtfeyA0RS/n1oQPE3YPW9J/Vx9UOJkXdynEECmP7Onzsz1/GS4SfZCS/gt58dOp9hcIpOiSqs9H5fh8R0SvMHa1cfh6JAYt46pJZZClXvrpzMeZ/Hg2p4dWmoVREe5E3MtRw+JQfS5kFbi9JYH8NTNiAwOPiaknUlidXLaLvLzlOQOy0f8u5R8m9IZApRxDLcHTGMVYsPsxscL0fEwT8G2/r6EZqVQDtDxAoZZQg7+/nuvejSVtcnU8P6lU+T44ljGn6dkHZcrnNOY9co8Lk2wYJd6pI60DgMICDzMk937s7eSmOADM1RMjQ59D8EfNDj4+Xd8fFy4hbTeNZMttsCQ1ViqD4cKWsJ257zoimllSNBVnTg3tgmZLJzlyYCAZ6dAw/+7kwgT40qUhjmwkFyWHyOiAyDGQu9faL4U+6JprtZZuuUlOb7wRaRFSGorsSIhX1hdc1LRClWsV/IXV7ppvg75CWZSF1QA/SGZYn/LTYZ+zyawUFcf+yA53FI5dX9hSoYv4FPLrDMW4jOQaXOh3q6XbMj0=
    on:
      branch: master
      condition: "`./scripts/checkTag.sh` = BETA"